### PR TITLE
Big rafactoring, again :)

### PR DESCRIPTION
**Pull request by samuelgarcia**
See #5 #6 #7 #8 #10.

### CODE REVIEW

**Comment by samuelgarcia** [comment]
@alejoe91 : this is a very first step.
If you could have a look mainly for the moment in comparisontools.py.
I destroy the do_matching and split it into several simple pieces.

**Comment by samuelgarcia** [comment]
@alejoe91 : I made the do_count in GTComparison independant of labelling this should be safer.
have a look please.

**Comment by samuelgarcia** [comment]
@alejoe91 @magland : the refactoring is quite big.
Basically I am using pandas a lot wich make the code very much simpler to read.

Could you have a look even if it is not finished ?
Please see first comparitools and mostly
  * make_match_count_matrix
  * make_agreement_scores
  * make_possible_match
  * make_best_match
  * make_hungarian_match

@magland : The class machinary is less important. But theses functions are important.

thanks a lot for helping.

**Comment by samuelgarcia** [comment]
Another thing. The counting is not anymore based on labels but directly the match_event_count.
It should speedup everything.

**Comment by samuelgarcia** [comment]
@magland @alejoe91 : This is finis. At least for now.
Could you have a look ?

**Comment by alejoe91** [comment]
@samuelgarcia @mhhennig should I merge? The bug in the matching was fixed and now it should be good right?

**Comment by samuelgarcia** [comment]
Normally this bug is fixed.
Please merge.
I will beack son with improveing doc, some rewritte in multicomparison and more ideas for study like inlcuding snr automatically.

**Pull request merged**
