### PR TITLE
Some new features in GT study.

### PR DESCRIPTION
**Pull request by samuelgarcia**
* Make SNR presistent in CSV file.
  * Various bug fix for label (FP/TP/FN)

### CODE REVIEW

**Comment by samuelgarcia** [comment]
Is it OK to merge this ?

**Comment by alejoe91** [comment]
@samuelgarcia I think dividing the delta_frames by 2 is correct. If you set delta_time to 3ms, then is [-1.5, 1.5] interval for each spike. So the way we compute it I believe it is correct to have delta_frames / 2, otherwise delta_time would be 6 ms in total. No?

**Comment by samuelgarcia** [comment]
@alejoe91 : but it is not consistent with this https://github.com/SpikeInterface/spikecomparison/blob/master/spikecomparison/comparisontools.py#L35.
I don't care delta_frames // 2 but we need to have same results with label and new method (base only on count).

**Comment by alejoe91** [comment]
I see, yes I agree it should be consistent. Do you agree that it should be Delta // 2 then?

**Comment by samuelgarcia** [comment]
No I don't agree.
The delta_times is the tolerance. The tolerence in each side is tottaly intuitive.
Tolerecne/2 on each side is not intuitive.

I disover that this parameters is rather sensible in mearec because off on the waveform peak alignement problem.

I really prefer to keep in this state. spikeforest which use this have a clear documentaiton here
https://spikeforest.flatironinstitute.org/metrics and deltaT is absolut so on each side.
We must align.

**Comment by alejoe91** [comment]
Ok! Then I think 3 Ms is a bit too much as default. Maybe 2 is better?

**Comment by samuelgarcia** [comment]
The deafult is **0.3ms** which is a bit low I would prefer 0.4 or 0.5.

**Comment by alejoe91** [comment]
Ahhh ok! I think. 0.5 is ok for me

**Comment by samuelgarcia** [comment]
I finally put 0.4 just to be in contradiction mood.
:)

**Comment by samuelgarcia** [comment]
I merge this?

**Pull request merged**
