### PR TITLE
This fix the fact that now rec.load_probe_file(prb_filename) return a SubRecordingExtractor

### PR DESCRIPTION
**Pull request by samuelgarcia**
This fix the fact that now rec.load_probe_file(prb_filename) return a SubRecordingExtractor.

It is a simplified load_probe_file version in the context of one group and all channel used.

Which is the case in ComparisonStudy

@colehurwitz @alejoe91 : it is a implss but faire fix of the problem I mention in spikeextractor.

### CODE REVIEW

**Comment by alejoe91** [comment]
What about this:

```
if isinstance(rec, se.SubRecordingExtractor):
    if isinstance(rec._parent_recording, se.BinDatRecordingExtractor):
        ...
else:
    if isinstance(rec, se.BinDatRecordingExtractor):
        ...
```

**Comment by alejoe91** [comment]
Otherwise I think that it's ok to have a `load_probe_file_in_place` in `spikeextractors`. Just be aware that in the current implementation you can't remove/reorder channels...

**Comment by samuelgarcia** [comment]
I known but in the context of Study it is totally OK because recordings copied in the folder are already recording simplified (channel remove).
I need this function only before run_sorter and the rec is always a BinDat and the also always a prb file.

Given theses limitation I think it is better to have this here and not in SE.

**Comment by colehurwitz** [comment]
I like `load_probe_file_in_place` for now. I think it works for this example. However, couldn't you modify the `channel_ids` to allow for removing and reordering channels? Or something like that.

**Comment by samuelgarcia** [comment]
Hi Cole.
In the GTStudy, this is not needed because it is done before writting to disk.

**Comment by samuelgarcia** [comment]
@alejoe91 @colehurwitz after ths PR https://github.com/SpikeInterface/spikesorters/pull/93 wa should merge also this one.

**Comment by samuelgarcia** [comment]
I will today merge this because spikesorters have been released.
So we will be able to work on docs for SI metapackage.

**Pull request merged**
