### PR TITLE
Use spikewidget for plot confusio matrix

### PR DESCRIPTION
**Pull request by samuelgarcia**

### CODE REVIEW

**Comment by samuelgarcia** [comment]
To make @alejoe91 happy.

**Comment by alejoe91** [comment]
@samuelgarcia why not just using spikewidget externally and completely remove the plot confusion matrix? 

It's the same:

```
cmp = sc.compare_....
W = sw.plot_confusion_matrix(cmp)
```

Spikewidgets retruns a widget object with figure and ax fields. I think it's better (for now) to keep plots separated.

**Comment by samuelgarcia** [comment]
Method is convinient in jupyter with autocompletion but I can live without.

For plotting I think I like the double apporach func + method. but wirttent with func.

**Comment by alejoe91** [comment]
in SW they are all functions, but they return the object. I think that if we start duplicating plotting functions it might become confusing.

Then the RecordingExtractor should have a wrapper of the plot time series and so on.. do you agree?

**Comment by samuelgarcia** [comment]
it is not a duplcate just a shortcut...

Why not to have this in spikeextractor if you want.

if it make you unhappy I can remove :)

**Comment by alejoe91** [comment]
then everything would depend on SW and it would break the dependency graph!!! :) 

Yes I kind of like plotting being stand alone. In case you wanted to keep it you should return the widget as output and document it etc. etc...

Also if you autocomplete on sw. you get all the functions so it's quite convenient as well. 

Please make me happy :)

**Comment by alejoe91** [comment]
ahahah fantastic! ready to merge?

**Comment by samuelgarcia** [comment]
I need 2 min of contemplation before the die of the plot_confusion method.

**Pull request merged**
