### PR TITLE
Copy pate from spiketoolkit.

### PR DESCRIPTION
**Pull request by samuelgarcia**

### CODE REVIEW

**Comment by samuelgarcia** [comment]
@alejoe91 @colehurwitz : I discoverd in the paper that we go for this.
So I started to port it.
I need to settle the travis.

@alejoe91 : when you did the travis . Did you make permission to all the team ?
EDIT : travis is automatic now only with the file. This maybe why we have 2 travis running on toolkit.

**Comment by colehurwitz** [comment]
I think 4/5 have agreed to the spikeinterface meta-package (which calls the other packages as indicated in the paper). We assumed that this is the direction that we would go since the majority are in favor of it (@magland has not given a new opinion on this meta package, but @alejoe91 is on board now).

I think we all agree on separating out spikecomparison so this is great.

**Comment by samuelgarcia** [comment]
I have also started spikeinterface package.

**Comment by samuelgarcia** [comment]
@alejoe91 : I have copy/paster your change done in toollkit.
I think we should merge this soon and make and remove comaprison/study from toolkit very soon before new changes.

**Comment by alejoe91** [comment]
@samuelgarcia one last change: in the `study` why do you use the `[#]` in the name?
https://github.com/SpikeInterface/spiketoolkit/blob/master/spiketoolkit/study/studytools.py#L224

Can we just make it a _? like rec1_mountainsort4.npz?

**Comment by alejoe91** [comment]
+ can you remove the confusion matrix plot? :)

There was a small bug fixed in SW (the labels of the axes was the opposite)

**Comment by samuelgarcia** [comment]
because '_' is very common in name I want somethin that never exists.
For instance I could have rec_names = ['noise_20uV', 'noise_30uv'] and this would mess up everthing.

**Comment by samuelgarcia** [comment]
For the confusion matrix : yes but in a separate PR please :)

**Comment by samuelgarcia** [comment]
I think we should merge this soon.
make a couple of PR if need and release very soon.
So we could build the spikeinterface package.

**Comment by alejoe91** [comment]
ok fair enough!merging :)

**Pull request merged**
